### ISSUE TITLE
BUG: JSON path does not work for iterations over lists of objects

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/morph-kgc#132]
####  What Happens?
if my JSON looks like this:
```
{
"owner": [
    {
    "name": "dgarijo",
    "type": "Person"

    }]
}
```
And I try to use the following mapping:
```
  Agent:
    sources:
      - main-source
    s: https://w3id.org/okn/i/Agent/$(owner.*.name)
    po:
      - [a, schema:$(owner.*.type)]
      - [schema:name, $(owner.*.name)]
```
No results are returned. However, this works with Matey. I tried other things like `$(owner[*].name)` but it does not work either.

#### To Reproduce
See above

#### Environment (please complete the following information):
 - Morph-KGC version: morph-kgc==2.3.1
