### ISSUE TITLE
BUG: Does morph-kgc provide support for using schema-qualified tables?

### ISSUE THREAD

**Issue by paoespinozarias** [oeg-upm/morph-kgc#89]
I need to access to a schema-qualified table from a Microsoft SQL DB. So, I need to do something similar to the first example shown in the following image taken from the [R2RML spec](https://www.w3.org/TR/r2rml/#physical-tables):
![image](https://user-images.githubusercontent.com/16767406/202721806-eae86615-2a16-450c-80bf-d4dbd4a41620.png)

However, despite that in the mapping file I have specified the schema and table to be accessed morph-kgc isn't able to generate the correct query. This is part of the mapping written in yarrrml syntax: 

````
sources:
  departments: 
     table: SCOTT.DEPT
     queryFormulation: mssql
````
The query that morph-kgc executes at runtime is:

````
[SELECT [Name] FROM [SCOTT.DEPT]]
````
However, the execution of such query throws the following execption: "Invalid object name 'SCOTT.DEPT' ".  Therefore, it seems that only a default schema is assumed (like the second example from the previous image) and SCOTT.DEPT is interpreted as an unqualified table name.

To solve this problem, I use a specific query instead:
````
sources:
  departments:
     query: SELECT [Name] FROM [SCOTT].[DEPT]
     queryFormulation: mssql
````

This alternative works, but it means that morph-kgc runs the full query in each mapping rule instead of the efficient query execution it normally runs which only extracts the required parameters in each mapping rule. 

Perhaps, there is another way of configuring such kind of schema-qualified table access, but I did not find any example in the morph-kgc documentation.
